version: "3"
services:
  staging:
    build:
      context: .
      args:
         - LOGIN=${LOGIN}
         - PASSWORD=${PASSWORD}
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  prod:
    build:
      context: .
      args:
         - LOGIN=${LOGIN}
         - PASSWORD=${PASSWORD}
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  ansible:
    build:
      context: ./ansible/
    tty: true
    volumes:
      - ./ansible:/home/ansible
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
