version: "3"
services:
  staging:
    build:
      context: .
      args:
         - LOGIN=${LOGIN}
         - PASSWORD=${PASSWORD}
    volumes:
    - ./ssh/sshd_config:/etc/ssh/sshd_config
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  prod:
    build:
      context: .
      args:
         - LOGIN=${LOGIN}
         - PASSWORD=${PASSWORD}
    volumes:
    - ./ssh/sshd_config:/etc/ssh/sshd_config
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
